### ISSUE TITLE
sum of squares / square of sums: check type

### ISSUE THREAD

**Issue by sbromberger** [exercism/julia#138]
> one last thing: on square of sum / sum of squares, one lesson I want to get across there is the use of `÷` instead of `/`. Could someone modify the test to check that the result is an int?

**Comment by SaschaMann** [comment]
Fixed in #139, thanks for the suggestion :)

**Comment by ScottPJones** [comment]
I'd actually tell them to use `div` first, and *then* explain how the Unicode symbol ÷ can be used for the same thing.
