### ISSUE TITLE
grains overflow

### ISSUE THREAD

**Issue by dhpollack** [exercism/julia#140]
The tests for the grain problem do not properly check whether the solution has accounted for the fact that 64th place causes an overflow.  The user should use an Int128 or UInt128 type.  I adjusted the tests as follows:

```
...
@testset "On squares" begin
    @testset "On square $s" for s = 1:64
        @test on_square(s) == Int128(2)^(s-1)
        @test total_after(s) == Int128(2)^s - 1
    end
end

@testset "Overflow Test" begin
    @test total_after(64) > total_after(30)
end
```

Having said that, I think you should change the tests to not give away the answer.  You don't need to check every square.  Just the first few, and the last few.  The canonical-data.json file does something like this rather than the exhaustive check used here.

**Comment by SaschaMann** [comment]
Thanks for the bug report!

> Having said that, I think you should change the tests to not give away the answer.

That's definitely true, and not something I thought of before. Usually I prefer more general tests over specific examples (like canonical-data tends to have) but giving away the solution is obviously not the right way to handle this.

I probably won't have time to fix this properly this week, but the changes you suggested would fix the immediate issue of overflow checking and strengthen the test suite in general. Could you submit a PR with those changes?

**Comment by dhpollack** [comment]
@SaschaMann I sort of misread your message before I created the pull request.  Do you want me to change it to be exactly what I suggested above?  I actually changed them to the canonical-data tests.

**Comment by dhpollack** [comment]
I actually just created a second pull.  Choose the one you want to use.  :-)

**Comment by SaschaMann** [comment]
The canonical-data tests are better, indeed. Sometimes there are so many it's tedious to manually add them (didn't check the file when I wrote that comment) and the 2nd option would be a quick hotfix, that's why I suggested it.

Thanks for fixing the issue! :)
