### ISSUE TITLE
Julia track - Rotational Cipher exercise has broken links

### ISSUE THREAD

**Issue by Daniel-EST** [exercism/julia#160]
Exercise's introduction has the following broken links:
[blog post](https://docs.julialang.org/en/stable/manual/metaprogramming/)
[Julia Manual](https://iaindunning.com/blog/julia-unicode.html)

I'm new to metaprogramming those tips could be very useful.

**Comment by iHiD** [comment]
If you add the text following text to the top of the PR, then this issue will get auto-closed when the PR gets merged:

> Closes https://github.com/exercism/julia/issues/160
