### ISSUE TITLE
Generation of exercise READMEs by configlet is not idempotent

### ISSUE THREAD

**Issue by Teo-ShaoWei** [exercism/julia#161]
From the [instruction to regenerate exercise READMEs](https://github.com/exercism/docs/blob/master/maintaining-a-track/regenerating-exercise-readmes.md), it seems to me that the following
```
bin/configlet generate .
```
should be an idempotent operation. However, this is not the case, and many exercise READMEs will be changed upon running this command on the current state of this repo.

This means that if we are creating a new exercise, we have to always run
```
bin/configlet generate . --only <stub>
```
which is ok but defeat the purpose of the simpler version.

**Comment by SaschaMann** [comment]
The way readmes are generated will change with v3, and I believe there will be better built-in checks for this
