### ISSUE TITLE
Add Pythagorean Triplet Exercise in Julia Track.

### ISSUE THREAD

**Issue by PseudoCodeNerd** [exercism/julia#185]
### Add Pythagorean Triplet  ~~and n-th Prime~~ Exercise in Julia Track.

I want to work on this and get this task in the Julia track.

-_GCI 2019_

N-th Prime was already taken,

**Comment by PseudoCodeNerd** [comment]
Cannot figure out how to print triplets with a given sum (multiple as in case 840) with Julia. 
Will try to complete an easier exercise right now.

**Comment by SaschaMann** [comment]
If it helps, you can take a look at implementations in other languages, like in Python: https://github.com/exercism/python/blob/master/exercises/pythagorean-triplet/example.py

Or if you have specific questions, please ask them and we can help you figure it out!

But yea, picking another one is fine too if you want
