### ISSUE TITLE
matching-brackets

### ISSUE THREAD

**Issue by chinglamchoi** [exercism/julia#206]

**Comment by SaschaMann** [comment]
@logankilpatrick already claimed this exercise (#195). Please choose another one or ask him if he started working on it already first to avoid duplicate work.

**Comment by logankilpatrick** [comment]
You’re welcome to do this one. It‘s quite difficult and I got about 85% done but then got sucked into another things.

**Comment by SaschaMann** [comment]
Closed by #211
