### ISSUE TITLE
Add high-scores exercise

### ISSUE THREAD

**Issue by josobar** [exercism/julia#212]
Manage a game player's High Score list.

Your task is to build a high-score component of the classic Frogger game, one of the highest selling and addictive games of all time, and a classic of the arcade era. Your task is to write methods that return the highest score from the list, the last added score and the three highest scores.

**Comment by josobar** [comment]
I can't seem to get the exercise to config.json. I downloaded the Julia repository and ran `new-exercise.jl` locally, but I get an error that says "could not run cofiglet." Am I running the program correctly?

**Comment by SaschaMann** [comment]
You need to download the configlet first: https://github.com/exercism/julia/blob/master/CONTRIBUTING.md#fetch-configlet

**Comment by josobar** [comment]
I ran the script and successfully installed configlet, but I still get the same error.

**Comment by josobar** [comment]
I was able to figure it out and `config.json` was edited successfully. Thank you.
