### ISSUE TITLE
robot simulator invalid test

### ISSUE THREAD

**Issue by dhpollack** [exercism/julia#224]
https://github.com/exercism/julia/blob/master/exercises/robot-simulator/runtests.jl#L47

`@test position(advance!(Robot((0, 0), SOUTH))) == Point(0, -1)` is an invalid test.  The `advance!` function is an inplace function as denoted by the exclamation point and thus should not return anything.  The `position` function on the other hand, should accept a `Robot` as a parameter.  Thus this test as written cannot pass with proper functions.  The test should be re-written as follows

```
r = Robot((0, 0), SOUTH)
advance!(r)
@test position(r) == Point(0, -1)
```

**Comment by cmcaine** [comment]
It's normal for mutating functions to return something appropriate, so I'm not sure this is wrong (see e.g. `reverse!`, `get!`).

We could clarify the expected API in the instructions, though.

**Comment by cmcaine** [comment]
We should probably make the tests expect a robot back from `turn_left` and `turn_right`, too.
