### ISSUE TITLE
Add tests to reverse-string to teach correct string handling

### ISSUE THREAD

**Issue by tobega** [exercism/julia#238]
I have brought this up centrally in https://github.com/exercism/problem-specifications/issues/1661 but it will hit each language differently, so it was suggested it might be changed just for Julia.

Since Julia is made to be able to handle strings properly, we shouldn't be encouraging solutions that treat strings as if they were arrays of bytes (as many of the elegant but too simple community solutions do). Incorrect handling of non-ASCII characters (or surrogate pairs if you use something like Java) is one of the biggest sources of bugs in the industry.

I propose adding at least a test with a multibyte UTF-8 character as is common in most European languages, e.g. "skåp" which becomes "påks" (this would make a difference in the Julia solutions, for example)

For even better benefit (for UTF-16 languages), it could be good to have a string containing a surrogate pair, e.g. "\uD834\uDD1E", a G-clef, which should come out as it was.

These two changes are easy to handle in Julia if you just treat strings with the proper respect.

I think that is enough, and it would probably be too difficult to also handle combining marks correctly, e.g. "as⃝df̅" should become "f̅ds⃝a", not "̅fd⃝sa" (from rosettacode.org)

**Comment by SaschaMann** [comment]
I like the idea, since it makes this exercise a lot more interesting.

Do you think students should be allowed to use `graphemes`/the Unicode stdlib in their solutions or should they implement it "from scratch" like in [Julia Base](https://github.com/JuliaLang/julia/blob/master/base/strings/unicode.jl#L658-L674)?

**Comment by cmcaine** [comment]
I think we could offer that as a bonus. It requires a bit of research to get right.

**Comment by cmcaine** [comment]
Opened a PR. It adds a compulsory test with a SMP plane character (:cat:) and bonus tests for graphemes.
