### ISSUE TITLE
Accumulate exercise confusing and flawed

### ISSUE THREAD

**Issue by MpdWalsh** [exercism/julia#256]
The Accumulate exercise says to implement the `accumulate` operation, but the instructions are akin to the `map` operation.

Accumulate: https://docs.julialang.org/en/v1/base/arrays/#Base.accumulate

Map: https://docs.julialang.org/en/v1/base/collections/#Base.map

Additionally, the test cases make no sense.

```
@testset "multiply" begin
    @test accumulate(collect(1:10), *) == [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
end
```

If it were the `accumulate` operation, the result would be `[1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800]`
And for `map` it would be `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` but mapping a binary operation to a single argument is... strange.

From what I can tell, the rest of the tests cases are similarly nonsensical. They seem to be either testing the binary operation performed on the element and itself again, or the element and its index in the collection.

**Comment by cmcaine** [comment]
Yeah, this is a bit of a mess. Some of the verbiage is from here: https://github.com/exercism/problem-specifications/blob/master/exercises/accumulate/description.md which is just describing `map`.

I think this exercise should be removed. An actual exercise implementing accumulate might be a bit interesting, but it will be confusing to students who have seen the exercise on other tracks and we'd have to rename it and stuff.

PR submitted.

**Comment by cmcaine** [comment]
And thanks for opening this issue!

**Comment by cmcaine** [comment]
The exercise will still be visible to you because you've started it, but it won't be offered as an option to new students any more.

**Comment by MpdWalsh** [comment]
Thanks for looking into it!
