### ISSUE TITLE
Deprecate transpose exercise?

### ISSUE THREAD

**Issue by cmcaine** [exercism/julia#258]
It's really weird. At a minimum I think we should emphasise the strangeness in the instructions, IMO.

Here's my solution to it, to explain the weirdness:

https://exercism.io/tracks/julia/exercises/transpose/solutions/0882224dd6864e448cc89762665ed7ee

```jl
"""
    transpose_strings(input)

Given an iterable of strings, interpret them as a matrix of characters and
transpose them returning a new iterable of strings.

The tricky business is in padding: we are expected to pad the output on the
left with spaces but strip spaces on the right while also preserving all
spaces in all columns.

So an input of:

["a c",
 "A",
 "12345"]


Yields:

["1Aa",
 "2  ",
 "3 c",
 "4",
 "5"]

"""
function transpose_strings(input)
    isempty(input) && return input
    maxlen = maximum(length, input)
    # Pad each line with null characters to the same length, then rotate
    map(eachrow(hcat(collect.(rpad.(input, maxlen, '\0'))...))) do row
        # Strip null bytes from the right,
        # then replace any remaining nulls with spaces
        replace(rstrip(join(row), '\0'), '\0' => ' ')
    end
end
```

**Comment by SaschaMann** [comment]
I agree it's a bit strange. Otoh while the solution is strange, it requires thinking about various edge cases. There might something else to be learned from this exercise if the padding is cleared up so that it can be solved with `transpose(s::String) = s` and `input'`.

**Comment by cmcaine** [comment]
It's tricky enough that a bunch of the community exercises pass the tests but don't obey this property (the tests happen to only require the last line to be stripped because the first line of the input is only ever at most one character shorter than the longest).

I think practicing how to do weird and silly things is worthwhile, because that is what a lot of programming is, but I think this problem is underspecified in the description and a lot of answers just end up bodging it.

**Comment by glennj** [comment]
I just noticed this got deprecated. The key is to ensure that each output row is _at least as long as the **next** one_.

**Comment by cmcaine** [comment]
Sure, constructing the rows of the transposed matrix in reverse order is a bit simpler, I hadn't thought of that. It doesn't change my point that this is a deeply weird exercise that most people get wrong, though :)
