### ISSUE TITLE
Tests for binary search don't enforce `by(key)`

### ISSUE THREAD

**Issue by tomerarnon** [exercism/julia#265]
It is possible to pass all the binary search tests with `lt(by(book[i]), key)`, rather than `lt(by(book[i]), by(key))`, which is what it should be. This is because the only `by` that is used is `round`. Adding the following will fail if `by` isn't used on they key
```
binarysearch([1.1, 2.9, 4.4, 5.5, 8.1, 9.0, 10.8], 9, by = abs2∘round) == 6:6
```
It is a copy-paste of another test, with `by` modified.

**Comment by SaschaMann** [comment]
Fixed by 8ab770c7519098f96a233e6f4aa9de0dfcc06542 and #267
