### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/julia#440]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/julia/runs/3339009172

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by SaschaMann** [comment]
Hi! 

> I thought it keeping the concept and removing the exercise would be the way to go.

There's an open PR for this. 

> Making empty files silences configlet, so that's what I'm doing now.

Please don't. Silencing configlet means those files will just be missed. They should either have proper content or not exist. The failure is desired behaviour.
