### ISSUE TITLE
Prepare 'robot-name' for v0.6

### ISSUE THREAD

**Issue by SaschaMann** [exercism/julia#46]
This exercise uses types and will need to be updated to the new type/struct system in v0.6

**Comment by aawray** [comment]
I guess testsets won't be changed,
OR we can use Base.VERSION to check the version in runtests.jl

Examples of type usage in Julia (trunk): https://github.com/JuliaLang/julia/blob/master/examples/juliatypes.jl

**Comment by SaschaMann** [comment]
Yeah, the tests should be fine but the example needs to be changed to `mutable struct`. I don't think having VERSION checks in the example is useful unless we support outdated versions as well, which imo doesn't make sense before v1.0.
