### ISSUE TITLE
Spoiler alert: rotational-cipher- working on v1.7, but hanging on exercism's v1.6

### ISSUE THREAD

**Issue by bardo84** [exercism/julia#469]
```julia
function rotate(n::Int, s::String)
    vc = collect(s)
    vc = rotate_c.(n, vc)
    String(vc)
end
function rotate(n::Int, c::Char)
    c = rotate_c(n, c)
end

function rotate_c(n, c)
    ai = Int('a')
    zi = Int('z')
    iu = isuppercase(c)
    c = lowercase(c)
    ci = Int(c)
    if ci in ai:zi
        i = (ci - ai + n) % (zi - ai + 1) + ai
        c = Char(i)
        return iu == 1 ? uppercase(c) : c
    else
        return c
    end
end
```

**Comment by SaschaMann** [comment]
What does hanging mean? Does it throw an error? Not finish in time?

Btw, if you wrap code in triple backticks you will get proper formatting in GH issues:

~~~markdown
```julia
# your code here
```
~~~

**Comment by bardo84** [comment]
Thx, forgot..
Yes, the code does not throw an error, but gets a time-out.

**Comment by SaschaMann** [comment]
Could you try running the tests again? If I copy your solution into the web editor, it finishes after a few sec with all tests passed.

**Comment by bardo84** [comment]
You are right, passing..
No idea, sorry for bugging and thx!

**Comment by SaschaMann** [comment]
No worries, might have been an issue with the infrastructure :)
