### ISSUE TITLE
robot-name: 1 test failing, how to proceed?

### ISSUE THREAD

**Issue by bardo84** [exercism/julia#470]
Since not all tests did pass, I cannot ask for help - mentoring is supposed to be for improvements only?
So how to proceed?

Possible constraints are not clear.
I could imagine a pseudorandom set of all possible permutations and subsequently emit these.
This would require a global counter - allowed?
Thx, great exercises!

**Comment by SaschaMann** [comment]
> Possible constraints are not clear.
> I could imagine a pseudorandom set of all possible permutations and subsequently emit these.
> This would require a global counter - allowed?

Yes, such a set and counter would be allowed and it's actually close to the recommended solution. If you get it working that way, a mentor can help you figure out how to optimise it.

Other than not using external packages/libraries, pretty much everything is allowed. Some things might not be a good idea for a number of reasons but a mentor would tell you that :)

---

> Since not all tests did pass, I cannot ask for help - mentoring is supposed to be for improvements only?
> So how to proceed?

There are a few options in general:

a) If you're working locally and use the CLI, you can submit the file and request mentoring anyway
b) You can check out community solutions by going to the following URL directly: `https://exercism.org/tracks/julia/exercises/robot-name/solutions` (this will include spoilers)

---

>Thx, great exercises!

That's nice to hear, thanks :)

**Comment by pjgoodall** [comment]
I may have missed it, but I didn't see anything saying I may not use packages. Where is this documented? Thanks...

**Comment by cmcaine** [comment]
You can make the local tests pass while using third-party packages, but the cloud test-runner that we provide doesn't bundle any third party libraries and doesn't allow your code to talk to the internet, so you can't install any.

Closing because I think this is answered.
