### ISSUE TITLE
Unable to view concepts page

### ISSUE THREAD

**Issue by miitchyy** [exercism/julia#478]
Hi team,

Apologies if this is not the right place to reach out.

I started the Julia track yesterday and after completing the first exercise I was told to visit the [concepts page](https://exercism.org/tracks/julia/concepts) but when I open that page I do not see any content (refer below image).
![Screenshot from 2021-12-21 20-41-58](https://user-images.githubusercontent.com/7676935/146916753-f9b39b60-69b7-4a17-8b17-d0b88ba7defe.png)

I have tried multiple browsers, different computers, and different operating systems to no avail.

Am I missing something?

Kind regards,
Mitchell O'Sullivan

**Comment by SaschaMann** [comment]
Hi!

Thanks for the bug report.

Concepts aren't available for the Julia track yet, it shouldn't prompt you to open that page. I'll move this issue to exercism/exercism as it's an issue with the website, not the Julia track.

**Comment by miitchyy** [comment]
Thanks for clearing that up @SaschaMann, that makes sense as to why there's nothing there!

To help remediate, I also found them linked on the [about page](https://exercism.org/tracks/julia/about) about half way down.

**Comment by ErikSchierboom** [comment]
Thanks both! We'll fix in a future update.
