### ISSUE TITLE
binary-search: instructions don't specify output format

### ISSUE THREAD

**Issue by stepinski** [exercism/julia#479]
@ErikSchierboom 
in binary search Julia exercise:
https://github.com/exercism/julia/blob/main/exercises/practice/binary-search/runtests.jl
the instruction is unclear - doesn't specify the output format
It's impossible to understand  what's expected from tests provided

**Comment by SaschaMann** [comment]
Hi, thanks for reporting this :)

The output mirrors Julia's own search functions: https://docs.julialang.org/en/v1/base/sort/#Base.Sort.searchsorted

We should probably use the same or similar examples in our instructions.

Do you want to submit a PR to improve the instructions?

**Comment by stepinski** [comment]
sure, will take care of it
