### ISSUE TITLE
Instructions on Panagram Exercise are incorrect

### ISSUE THREAD

**Issue by SirZayers** [exercism/julia#488]
The Panagram exercise's instructions say that the tests will only input ASCII characters, this is wrong. Test 14 specifically tests the solution on its handling of non ASCII characters.

**Comment by Francehelder** [comment]
Test 14 is wrong.
I made my code to work with non-ASCII letters, but fails.

```
@testset "pangram with more than 26 letters (if case sensitive)" begin
    @test ispangram("the 1 quick brown fox jumps Over the 2 lazy dogs")
end
@testset "letters that aren't part of ASCII" begin
    @test !ispangram("the 1 qüick bröwn föx jümps över the 2 läzy dögs")
end
```

**Comment by cmcaine** [comment]
@Francehelder can you provide the code for your solution, please? Do you think `ispangram("the 1 qüick bröwn föx jümps över the 2 läzy dögs")` should return true or false?
