### ISSUE TITLE
ISBN Verifier

### ISSUE THREAD

**Issue by gpucce** [exercism/julia#503]
Hello,

In the ISBN verifier exercise, in the way the tests are designed I think there is no way of getting around having two occurrences of `replace(s, "-"=>"")` or equivalent without a `try ... catch` statement. 

If this is the case and I am not missing something, maybe it is worth writing an hint in the description or changing the tests so it is possible?

I can make the PR if it is something that would make sense.

**Comment by cmcaine** [comment]
Hello!

Why do you particularly want to avoid calling replace in two places?

If you do want to call it just the once you can do so without a try/catch. I think what's tripping you up is that you can't reuse ISBN(s) in isvalid(ISBN, s) without a try/catch and yet you don't want to duplicate the code in the ISBN function. But what if you had a third function?

Does that help?

Regarding a hint in the description, I don't think we are pushing students to use replace only once or avoid try/catch, so I'm not sure we need one?

Anyone wanting to improve their solution can always request mentoring :)

Looking at the description, I think our main issue is that we don't specify the problem very completely (you have to read the tests for that).

We also suggest a truly horrendous bonus task: "Implement show(io::IO, isbn::ISBN) to print the ISBN in the standard format with dashes." Where to place the dashes depends on pages and pages of data about different worldwide publishers, etc cos each part of the ISBN is variable length.

We should probably remove that, tho I think that bit is only visible in the instructions.md that doesn't get used? I forget how that works.

**Comment by gpucce** [comment]
Hi thanks for the answer! I had not thought about that indeed, I really wanted to use those two together :) 

However, just so I don't miss the point again with a third function I would need to use that function twice or can I avoid that?

The strange bonus track I have not noticed honestly so it should be hidden. 

For sure I had to read the tests while doing the exercises otherwise the `DomainError` would have never crossed my mind.

**Comment by cmcaine** [comment]
ISBN(s) and isvalid(ISBN, s) will each need to call your third function at least once each. Further details (not too spoilery) below.

<details>

The removal of the try/catch is simply by replacing a function that will *throw* an error with one that *returns* an error type.

I would implement this by defining `Base.tryparse(::Type{ISBN}, s)`, but of course you don't need to add a method to that existing function you could write something like `tryparse_isbn(s)` or `isbn_or_nothing(s)` or whatever you'd like to call it.

</details>

**Comment by gpucce** [comment]
Thanks so much! This is the solution I didn't know existed :)

**Comment by SaschaMann** [comment]
```
# It doesn't make any sense to me for an ISBN to be a String - basically none of the String API makes sense for an ISBN.
# But the tests require this, so whatever.
```

`isvalid` is only defined on strings by default, which is why I think I added that back then. But I agree there's no real need for it, feel free to remove that test.

**Comment by SaschaMann** [comment]
> Personally, I would define only a constructor and have it throw errors.

That sounds reasonable. Do you want to submit a PR to change it?

**Comment by gpucce** [comment]
If you want and there is no rush I can try to make the PR, I think I might have understood the point. Otherwise I will solve the exercise again after you change it!

**Comment by cmcaine** [comment]
I'll do it. Thanks for engaging!
