### ISSUE TITLE
BinarySearch tests can be improved

### ISSUE THREAD

**Issue by gpucce** [exercism/julia#507]
These two functions:
1)
```
function binarysearch(a, x::T; by = nothing, lt = (<), rev = false) where T
    l = length(a)
    if !isnothing(by)
        a = by.(a)
        x = by(x)
    end
    a = rev ? reverse(a) : a
    l == 0 && return a
    if l == 1
        a[1] == x && return 1:1
        return T[]
    end
    bottom = 1
    top = l
    while bottom < top
       if top - bottom == 1
	    if bottom == 1
	        top = bottom
	    else
		bottom = top
	    end
	end
        mid = bottom + round(Int, (top - bottom) / 2)
        if lt(a[mid], x)
            bottom = mid
		elseif lt(x, a[mid])
            top = mid
        else
            idx1 = mid
            idx2 = mid
            while (idx1 - 1 > 1) && a[idx1-1] == x
                idx1 -= 1
        end
            while (idx2 + 1 < l) && a[idx2+1] == x
                idx2 += 1
            end
        return if !rev
		idx1:idx2
		else
			l - idx1 + 1:l - idx2 + 1
		end
        end
    end
	return T[]
end
```
2)
```
function binarysearch(a, x; by = nothing, lt = (<), rev = false)
    l = length(a)
    if !isnothing(by)
        a = by.(a)
        x = by(x)
    end

    rev && (lt = >)
    l == 0 && return a
    if l == 1
        a[1] == x && return 1:1
        return 1:0
    end

    bottom = 1
    top = l
    while bottom ≤ top
        mid = (bottom + top) ÷ 2
        if lt(a[mid], x)
            bottom = mid + 1
        elseif lt(x, a[mid])
            top = mid - 1
        else
            return mid:mid
        end
    end
    return bottom:top
end
```

Behave differently on  `v = [1, 2, 40, 40, 40, 500, 600]` but both pass the tests and the second one has not the expected behaviour.

I can try to add more tests myself if it makes sense!

**Comment by cmcaine** [comment]
Can you describe the differences? Please feel free to add tests :)

**Comment by gpucce** [comment]
The first tries to return all elements equal to `x` while the second only the first value equal to `x` it finds so if the first is called `binarysearch1` and the second is `binarysearch2`

`binarysearch1(v) == 3:5`
`binarysearch2(v) == 4:4`

This is for a specific case however I don't that either of the two words as expected in general.

**Comment by SaschaMann** [comment]
The first one would be expected, in line with `searchsorted`:

```julia
julia> searchsorted(v, 40)
3:5
```

Currently the tests only tests for one match, requiring them to work for several matches would expand the scope of the exercise a bit. I'm not sure if it'd complicate it too much.

This might be worth discussing in [the shared problem specification repo](https://github.com/exercism/problem-specifications/) as well.

PRs that add these cases are welcome regardless of the above, we can always make them optional bonus tasks if we change our mind :)

**Comment by cmcaine** [comment]
I think a useful PR might amend the description to clarify that just the first match is required / the student may assume that the target value is only present once in the vector.

Then a bonus task about repeated target elements.

**Comment by gpucce** [comment]
Hopefully in the next few days I will open a PR with the description and the tests with `@test_skip` like the other bonus tests.

**Comment by SaschaMann** [comment]
It'd be ideal if you also add the description changes upstream in problem-specifications so that other tracks will benefit as well.

**Comment by cmcaine** [comment]
I'm not sure what we'd do to conditionally enable the tests. Previously we've looked for the definition of functions required for the bonus task (in rotational-cipher), or for the definition of a variable called "enable_bonus_tests" (in circular-buffer).

Or we just mark the bonus tests with `@test_skip`, but that's not very good for people using the web editor.

I think for this exercise, we should probably look for a variable called `enable_bonus_tests` and add a note to the description saying to add `enable_bonus_tests = true` to the bottom of your exercise file to enable the bonus tests.

**Comment by SaschaMann** [comment]
> I think for this exercise, we should probably look for a variable called enable_bonus_tests and add a note to the description saying to add enable_bonus_tests = true to the bottom of your exercise file to enable the bonus tests.

`circular-buffer` has an example of this: https://github.com/exercism/julia/blob/c487eaa4a1c7d993cde2084e8d650efed3a3f978/exercises/practice/circular-buffer/runtests.jl#L140-L144

**Comment by gpucce** [comment]
So the description in julia already has this **assume a single element** whereas the instructions don't in the sense that there is mention to replicate searchsorted with examples of multiple matches. Should I add the comment on the single match to the instructions? 

Also sorry if this question comes late but I had not noticed a difference between description and instructions, does the description show somewhere on the exercism web-page?

**Comment by cmcaine** [comment]
We have six exercises that have markdown files in `.meta`, but I think these are all ignored by the tooling. [The documentation](https://exercism.org/docs/building/tracks/practice-exercises) says to provide markdown files in the `.docs` directory.

Julia-specific content for the exercise should go in `.docs/instructions.append.md` if it can naturally be added at the end of the instructions or in `.docs/instructions.md` if it cannot. `.meta/description.md` should be removed (you can do this in your PR).
