### ISSUE TITLE
Rational Number test fail---runtests.jl

### ISSUE THREAD

**Issue by iamforerunner** [exercism/julia#510]
in runtests.jl file line 111-112
    
for a in -5:5, b in -5:5, c in -5:5
        a == b == 0 && continue
"a ==" should be removed

the same as line 124
for d in -5:5
        c == d == 0 && continue

"c ==" should be removed too

**Comment by SaschaMann** [comment]
1//0 is a valid rational number in Julia, it behaves similarly to Inf in floating point numbers. Only 0//0 is meant to cause an error, which is why the ordering tests skip those cases.
