### ISSUE TITLE
lasagna: remove TODO from `introduction.md`

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/julia#565]
The `docs/introduction.md` document contains the following Markdown:

```
## Annotations

<!-- TODO: These are not concepts/concept headings, but what are they? -->

### Types

...

### Comments
```

I think want we want here is to have:

```
## Types

...

## Comments
```

**Comment by glennj** [comment]
It appears there's no "basics" concept associated with this exercise.

**Comment by glennj** [comment]
Please assign this to me.

**Comment by glennj** [comment]
> It appears there's no "basics" concept associated with this exercise.

This is not true: the first concept is `functions`
