### ISSUE TITLE
Add key features

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/julia#575]
To help showcase Julia's strengths, which can help students decide whether to join the track, key features should be added.
See https://exercism.org/docs/building/tracks/config-json#h-key-features for more information

**Comment by SaschaMann** [comment]
They already exist in `concepts.wip` https://github.com/exercism/julia/blob/d680ce67433895f1be8083ef79557f4679bc484a/concepts.wip/config.json#L375-L405
