### ISSUE TITLE
Port additional exercises?

### ISSUE THREAD

**Issue by BNAndras** [exercism/julia#675]
I'd like to start porting these exercises over the next few weeks.

- [ ] Bottle Song
- [ ] High Scores
- [ ] Micro Blog
- [ ] Strain
- [ ] Queen Attack
- [x] Eliud's Eggs
- [x] Protein Translation
- [x] Resistor Color
- [x] Resistor Color Duo
- [x] Space Age
- [x] Two Fer

**Comment by rainerrodrigues** [comment]
Hi @BNAndras , can I contribute?

**Comment by BNAndras** [comment]
Sure, this list might be out of date though so double check that exercises aren’t implemented anyway
