### ISSUE TITLE
Progress of Verbose Unit Testing for Comprehensive Testing Summary

### ISSUE THREAD

**Issue by yctai1994** [exercism/julia#684]
To: @ErikSchierboom

This issue tracks the progress of enhancing the unit testing verbosity to provide a more comprehensive testing summary, which is particularly beneficial for CLI users.

[Here](https://github.com/exercism/julia/pull/680) is a demo.

- - -

A [branch](https://github.com/yctai1994/exercism-julia/tree/yctai1994) contains the commits, which refer to the following progress.

- [ ] accumulate
- [ ] acronym
- [ ] all-your-base
- [ ] allergies
- [ ] alphametics
- [x] anagram
- [ ] armstrong-numbers
- [ ] atbash-cipher
- [ ] binary-search
- [ ] bob
- [ ] circular-buffer
- [x] clock
- [x] collatz-conjecture
- [x] complex-numbers
- [ ] custom-set
- [x] darts
- [x] difference-of-squares
- [ ] dnd-character
- [ ] etl
- [ ] gigasecond
- [ ] grains
- [x] hamming
- [x] hello-world
- [ ] isbn-verifier
- [x] isogram
- [x] killer-sudoku-helper
- [ ] largest-series-product
- [x] leap
- [ ] luhn
- [ ] matching-brackets
- [ ] minesweeper
- [x] nucleotide-count
- [x] pangram
- [ ] pascals-triangle
- [ ] perfect-numbers
- [ ] phone-number
- [ ] prime-factors
- [x] pythagorean-triplet
- [x] raindrops
- [ ] rational-numbers
- [ ] resistor-color-trio
- [x] reverse-string
- [x] rna-transcription
- [ ] robot-name
- [ ] robot-simulator
- [ ] roman-numerals
- [x] rotational-cipher
- [ ] run-length-encoding
- [x] saddle-points
- [x] scrabble-score
- [x] secret-handshake
- [ ] sieve
- [ ] spiral-matrix
- [ ] square-root
- [ ] sum-of-multiples
- [ ] transpose
- [ ] triangle
- [ ] trinary
- [ ] word-count

**Comment by ErikSchierboom** [comment]
Awesome!

**Comment by depial** [comment]
Closing this issue as complete since [PR #723](https://github.com/exercism/julia/pull/723) and [PR #111](https://github.com/exercism/julia-test-runner/pull/111) implemented this update.
