### ISSUE TITLE
Add new exercise related to Plotting?

### ISSUE THREAD

**Issue by rainerrodrigues** [exercism/julia#708]
I was wondering if it would be feasible to charter a new exercise for plotting to teach the concept of good visualization particularly in Julia?

**Comment by depial** [comment]
I'm not sure what you had in mind, but I believe you would have to design an exercise which can be tested objectively and programmatically for it to be feasible here.

If you're unfamiliar with exercise testing capabilities/limitations, here's the link to the testing package used on Exercism: [Unit Testing](https://docs.julialang.org/en/v1/stdlib/Test/)
