### ISSUE TITLE
New practice exercises available to add

### ISSUE THREAD

**Issue by depial** [exercism/julia#714]
I've made a couple of practice exercises which are in [this fork](https://github.com/depial/julia) and only need reviewing. If someone would like to use the code to add them to the track, feel free to take as much of it as you would like and modify it as you please (the only thing I ask is that I **not** be listed as author/contributor). The list of available exercises is below. Those with a PR open have a link.

## New practice exercises from Exercism problem-specifications

- [x] Binary Search Tree
- [x] Two Bucket
- [x] Dominoes
- [x] Change
- [x] Connect
- [x] Game of Life
- [x] Wordy
- [x] Matrix
- [x] Palindrome Products

The above are made according to the problem specifications. However, I may include a file `supplemental.jl` in the `.meta` folder with alternate/extra testing (to be used as desired). The file might also contain other potentially useful code I've written along the way.

## New practice exercises from scratch

- [x] [Perceptron](https://github.com/exercism/julia/pull/759)

The above will likely need a more thorough review.

If there are any questions about any of the code, I'd be happy to participate in the review process.

**Comment by ErikSchierboom** [comment]
> However, I may include a file supplemental.jl in the .meta folder with alternate/extra testing (to be used as desired)

We have an existing system for allowing students to run bonus tests: https://github.com/exercism/julia/blob/main/exercises/practice/circular-buffer/runtests.jl#L141-L265

**Comment by depial** [comment]
The `supplemental.jl` file (if it exists) is not meant for students (or to be included in the final exercise). It is for anyone who is porting the exercise. It's just extra material which could be useful/added during the review process.

**Comment by ErikSchierboom** [comment]
Right. Okay that makes sense then.

**Comment by depial** [comment]
The next exercise [(binary-search-tree)](https://github.com/exercism/julia/pull/739) is available for review

**Comment by depial** [comment]
New practice exercise [two-bucket](https://github.com/exercism/julia/pull/749) is now available for review

**Comment by depial** [comment]
New practice exercise [dominoes](https://github.com/exercism/julia/pull/750) is now available for review

**Comment by depial** [comment]
New practice exercise [change](https://github.com/exercism/julia/pull/754) is now available for review

**Comment by depial** [comment]
New practice exercise [game-of-life](https://github.com/exercism/julia/pull/755) is now available for review

**Comment by depial** [comment]
New practice exercise [wordy](https://github.com/exercism/julia/pull/756) is now available for review.

**Comment by depial** [comment]
New practice exercise [matrix](https://github.com/exercism/julia/pull/757) is now available for review

**Comment by depial** [comment]
New practice exercise [palindrome-products](https://github.com/exercism/julia/pull/758) is now available for review

**Comment by depial** [comment]
New practice exercise [perceptron](https://github.com/exercism/julia/pull/759) is available for review.

**Comment by depial** [comment]
Closing issue as all practice exercises have been reviewed.
