### ISSUE TITLE
Julia logo missing from website

### ISSUE THREAD

**Issue by depial** [exercism/julia#719]
I'm not sure if this is an issue, but on the website, where other languages have their logo, Julia just has an image of (default?) train tracks.

![image](https://github.com/exercism/julia/assets/91621102/2b97a20e-0670-463c-bd37-2def0b8aba16)

**Comment by lcscosta** [comment]
Hi @depial, I'm not able to reproduce this error. 

![Captura de tela de 2024-04-02 01-42-28](https://github.com/exercism/julia/assets/45444800/7bebb8fa-45c5-411e-96f5-4498898168d7)

But looking at the HTML, we can see that there is an error dealing that uses a default .svg.

![Captura de tela de 2024-04-02 01-44-35](https://github.com/exercism/julia/assets/45444800/66d204c5-c449-4a5b-ac43-6c04dad6d5fb)

Possible, for some reason, your browser don't find the logo and use default as a substitute.

**Comment by depial** [comment]
Interesting. I didn't think it was a browser issue since it only does it with Julia and is everywhere on the track.

![image](https://github.com/exercism/julia/assets/91621102/0f033248-2511-46b8-939f-fee54fe30de0)

However, I opened a private window and (without signing into Exercism) this error doesn't seem to occur, so it does indeed look local.
