### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by iHiD** [exercism/julia#776]
@colinleach, @depial You both qualify to be maintainers here. Thank you for your hard work! Would you like to join?

**Comment by iHiD** [comment]
(cc @depial - sorry misspelt your username at first)

**Comment by colinleach** [comment]
Firstly, I would be honoured.

Secondly, @BethanyG has been *quite strongly* twisting my arm to get more involved. If I refuse she may never speak to me again - nobody wants that!

**Comment by depial** [comment]
I'm happy to help wherever I can since I really like your mission. Feel free to sign me up :)

**Comment by BethanyG** [comment]
@colinleach  -- Happy to help/review/advise - especially on the learning syllabus.  🙂   Although you and depial have done considerably more work thus far, and are better Julia programmers than I.

**Comment by iHiD** [comment]
Awesome. Thank you both.

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)

**Comment by depial** [comment]
Cheers!
