### ISSUE TITLE
The `.github/CODEOWNERS` file probably needs updating

### ISSUE THREAD

**Issue by colinleach** [exercism/julia#777]
Current contents:

```
# Colin doesn't want to receive botspam
.github                 @exercism/maintainers-admin

# Code owners
.github/CODEOWNERS      @exercism/maintainers-admin

# Changes to `fetch-configlet` should be made in the `exercism/configlet` repo
bin/fetch-configlet     @exercism/maintainers-admin
```

This is about 2 years old (the Colin it refers to is a different one). The `maintainers-admin` group is just Erik, which is no longer appropriate. What's the best thing to change it to?

My first thought was @exercism/cross-track-maintainers, but I notice the equivalent file on the R track has the same problem.  There may be others. Would it be better for someone to update `maintainers-admin`, or does that have bad side effects??

**Comment by BNAndras** [comment]
A quick search of other Exercism repos with `.github/CODEOWNERS` files still shows `@exercism/maintainers-admin` for the non-tooling-specific track repos.

**Comment by colinleach** [comment]
I'm too clueless to understand quite what bad effects this will have, but I strongly suspect there will be bad effects.

Not that anyone doubted how central Erik has been!

**Comment by SleeplessByte** [comment]
Normalised by https://github.com/exercism/julia/pull/778
