### ISSUE TITLE
Add femtocleaner

### ISSUE THREAD

**Issue by SaschaMann** [exercism/julia#92]
@kytrinyx Could you install the [femtocleaner app](https://github.com/JuliaComputing/FemtoCleaner.jl) for this repo, please? I don't have the permissions to do it.

It's a bot that cleans up Julia code and deals with a lot of upgrades/deprecations between versions. It saves a lot of time when migrating to a newer Julia version.

**Comment by kytrinyx** [comment]
Oh, yes! I saw it mentioned a couple of weeks ago, and it looks fantastic.

Done.

**Comment by SaschaMann** [comment]
Thank you :)
