### ISSUE TITLE
De-duplicate the exercise UUIDs

### ISSUE THREAD

**Issue by Teo-ShaoWei** [exercism/julia#95]
I ran `bin/configlet lint .` and it warns that exercise UUIDs must be unique across language tracks. I checked `config.json` and yes the listed UUIDs are all inside.

What we need to do, is to replace each affected UUID in `config.json` with a new one generated using `bin/configlet uuid`.

Currently nothing really breaks from it, and it is a fairly straightforward task. I think it's a good exercise for newcomer to onboard or for Hacktoberfest =P

Any takers who want to clarify about this task, feel free to sound out and we will guide you along =)

Meanwhile, the contributors might want to take note and generate a new UUID for new exercise contributed from now on.

**Comment by SaschaMann** [comment]
Which exercise has a duplicate UUID? Travis runs the configlet as well and should fail the build if there's a duplicate UUID but the builds are all working fine.

**Comment by Teo-ShaoWei** [comment]
Oh no... then it might be my setup... Almost all exercises have UUID clash with another track... I will investigate what could went wrong on my side.

Do you see the same when you run `bin/configlet lint .`?

**Comment by Teo-ShaoWei** [comment]
Sorry this should be a false alarm, did a [search](https://github.com/search?utf8=%E2%9C%93&q=org%3Aexercism+a668410d-41aa-4710-a68f-54521da6486d+extension%3Ajson&type=Code&ref=advsearch&l=&l=) and seems like only the Julia package is using this UUID despite it being flagged on my system. But I really dunno why this is happening.

From the [code](https://github.com/exercism/configlet/blob/master/cmd/lint.go), seems like `bin/configlet lint .` directly calls the Exercism UUID validation API, so it shouldn't have anything to do with other repos on my system. All I can think of is my repo is "dirty" or deem to be not of Julia track, but the lint error still occurs even if I checkout `master`.

Anyway let's close this issue. Apologies once again.

**Comment by SaschaMann** [comment]
I don't see errors locally. That sounds strange indeed. You could open an issue in the configlet repo.

> Apologies once again.

No need to apologise!
